universe = docker
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

executable = run_submit.sh
transfer_input_files = run_submit.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = runlogs/submit.$(ClusterId).$(ProcId).out
error = runlogs/submit.$(ClusterId).$(ProcId).err
log = runlogs/submit.$(ClusterId).log

request_CPUs = 1
request_memory = 4G
request_disk = 5G

requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
